images:
  gitea: "10.1.40.43:5000/gitea/gitea:1.12.2"
  postgres: "10.1.40.43:5000/postgres:11"
  memcached: "10.1.40.43:5000/memcached:1.5.19-alpine"
  imagePullPolicy: IfNotPresent

service:
  http:
    serviceType: NodePort
    port: 3000
    nodePort: 30280
    externalPort: 30280 
    externalHost: 10.1.40.43
  ssh:
    serviceType: NodePort
    port: 22
    nodePort: 30220
    externalPort: 30220
    externalHost: 10.1.40.43

resources:
  gitea:
    requests:
      memory: 100Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
  postgres:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

persistence:
  enabled: true
  giteaSize: 8Gi
  postgresSize: 5Gi
  accessMode: ReadWriteMany
  annotations:
    "helm.sh/resource-policy": keep

